package main;

public interface C {
    int ROAD_WIDTH = 1000;
    int ROAD_HEIGHT = 723;

    int CAR_COMING_TIME = 5;
    int CAR_CONTINUE_TIME = 5;

    int TRAFFIC_LIGHT_TIME_IN_GREEN = 10;
    int TRAFFIC_LIGHT_TIME_IN_YELLOW = 3;

    String LEFT_RED = "LEFT_RED";
    String LEFT_GREEN = "LEFT_GREEN";
    String LEFT_YELLOW = "LEFT_YELLOW";

    String RIGHT_RED = "RIGHT_RED";
    String RIGHT_GREEN = "RIGHT_GREEN";
    String RIGHT_YELLOW = "RIGHT_YELLOW";

    String FRONT_RED = "FRONT_RED";
    String FRONT_GREEN = "FRONT_GREEN";
    String FRONT_YELLOW = "FRONT_YELLOW";

    String BACK_RED = "BACK_RED";
    String BACK_GREEN = "BACK_GREEN";
    String BACK_YELLOW = "BACK_YELLOW";

    String TRAFFIC_LIGHT_IS_IN_RED = "TRAFFIC_LIGHT_IS_IN_RED";
    String TRAFFIC_LIGHT_IS_IN_GREEN = "TRAFFIC_LIGHT_IS_IN_GREEN";
    String TRAFFIC_LIGHT_IS_IN_YELLOW = "TRAFFIC_LIGHT_IS_IN_YELLOW";

    String LEFT_TRAFFIC_LIGHT = "LEFT_TRAFFIC_LIGHT";
    String RIGHT_TRAFFIC_LIGHT = "RIGHT_TRAFFIC_LIGHT";
    String FRONT_TRAFFIC_LIGHT = "FRONT_TRAFFIC_LIGHT";
    String BACK_TRAFFIC_LIGHT = "BACK_TRAFFIC_LIGHT";

    String CAR_FROM_LEFT = "CAR_FROM_LEFT";
    String CAR_FROM_RIGHT = "CAR_FROM_RIGHT";
    String CAR_FROM_FRONT = "CAR_FROM_FRONT";
    String CAR_FROM_BACK = "CAR_FROM_BACK";

    String ALL_RED = "ALL_RED";
}
